# Generated by Django 3.0 on 2021-06-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210618_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='database',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
